beosztas/beo_admin/urls.py
from django.conf.urls import url

from . import views

app_name= 'beo_admin'
urlpatterns = [
    url(r'^create_shifts/$', views.create_shifts, name='create_shifts'),
    url(r'^finalize_shifts/$', views.finalize_shifts, name='finalize_shifts'),
    url(r'^manage_users/$', views.manage_users, name='manage_users'),
    url(r'^last_month_stat/$', views.last_month_stat, name='last_month_stat'),
]

beosztas/beosztas/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.views.generic.base import TemplateView

urlpatterns = [
    url(r'^$', TemplateView.as_view(template_name='home.html'), name='home'),
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include('users.urls')),
    url(r'^users/', include('django.contrib.auth.urls')),
    url(r'^beo_admin/', include('beo_admin.urls')),
]

beosztas/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'', include('login.urls')),
    url(r'^admin/', admin.site.urls),
]

beosztas/users/urls.py
from django.conf.urls import url

from . import views

app_name= 'users'
urlpatterns = [
    url(r'^signup/$', views.signup, name='signup'),
    url(r'^add_request/$', views.add_request, name='add_request'),
    url(r'^weekly_shift/$', views.weekly_shift, name='weekly_shift'),
    url(r'^late_request/$', views.late_request, name='late_request'),
    url(r'^swap/$', views.swap, name='swap'),
]

beosztas/templates/add_request.html
{% extends 'base.html' %}

{% block content %}
  <h2>Ráérés megadása</h2>
  <p>
    {% if request_error %}
    {{ request_error }}
    {% endif %}
  </p>
  <form method="post">
    {% csrf_token %}
    <p>{{ week }}. hét<p>
    <table>
      <tr>
        <th>Nap</th>
        <th>Műszak</th>
        <th>Óra</th>
      </tr>
      {% for form in daily_request_forms %}
        <tr>
          {% for field in form %}
            <td>{{ field }}</td>
          {% endfor %}
        </tr>
      {% endfor %}
    </table>
    <button type="submit">Elküld</button>
  </form>
{% endblock %}

beosztas/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'beo_admin/base.css' %}">
  <title>{% block title %}Beosztas App{% endblock %}</title>
</head>
<body>
  <main>
    {% block content %}
    {% endblock %}
  </main>
</body>
</html>

beosztas/templates/create_shifts.html
{% extends 'base.html' %}

{% block content %}
  {% if form_error %}
    <p style="color:red">{{ form_error }}</p>
  {% endif %}
  {% if daily_shift_forms %}
    <form action="{% url 'beo_admin:finalize_shifts' %}" method="post">
      {% csrf_token %}
      <button type="submit">Közzétesz</button>
    </form>
  {% endif %}
  {% for daily_shift_form in daily_shift_forms %}
  <div class="floated_divs" style="float:left">
      <form action="{% url 'beo_admin:create_shifts' %}" method="post">
      {% csrf_token %}
      {{ daily_shift_form.management_form }}
      {{ daily_shift_form.as_ul}}
      <button type="submit">Módosít</button>
    </form>
  </div>
  {% endfor %}
{% endblock %}

beosztas/templates/home.html
{% extends 'base.html' %}

{% block title %}Home{% endblock %}

{% block content %}
{% if user.is_authenticated and user.is_staff %}
  Helló {{ user.username }}!
  <p><a href="{% url 'beo_admin:create_shifts' %}">Beosztás készítése</a></p>
  <p><a href="{% url 'beo_admin:manage_users' %}">Alkalmazottak</a></p>
  <p><a href="{% url 'beo_admin:last_month_stat' %}">Előző havi statisztika</a></p>
  <p><a href="{% url 'logout' %}">Kilépés</a></p>
{% elif user.is_authenticated %}
  Helló {{ user.username }}!
  <p><a href="{% url 'users:add_request' %}">Ráérés megadása</a></p>
  <p><a href="{% url 'users:weekly_shift' %}">Beosztásaim</a></p>
  <p><a href="{% url 'users:late_request' %}">Késedelmes igény felvétele</a></p>
  <p><a href="{% url 'users:swap' %}">Csere vagy leadás</a></p>
  <p><a href="{% url 'logout' %}">Kilépés</a></p>
{% else %}
  <p>Nem vagy bejelentkezve</p>
  <a href="{% url 'login' %}">Belépés</a>
  <a href="{% url 'users:signup' %}">Regisztráció</a>
{% endif %}
{% endblock %}

beosztas/templates/manage_users.html
{% extends 'base.html' %}

{% block content %}
  <h2>Felhasználók</h2>
    <table>
      <tr>
        <td>Felhasználónév</td>
        <td>E-mail cím</td>
        <td>Vezetéknév</td>
        <td>Keresztnév</td>
      </tr>
      {% for user_row_form in user_row_forms %}
      <tr>
        <form method="post">
        {% csrf_token %}
          {% for field in user_row_form %}
            <td>{{ field }}</td>
          {% endfor %}
          <td><button type="submit">Törlés</button></td>
        </form>
      </tr>
      {% endfor %}
    </table>
{% endblock %}

beosztas/templates/signup.html
{% extends 'base.html' %}

{% block content %}
  <h2>Regisztráció</h2>
  <form method="post">
    {% csrf_token %}
    {% for field in form %}
      <p>
        {{ field.label_tag }}<br>
        {{ field }}
        {% if field.help_text %}
          <small style="color: grey">{{ field.help_text }}</small>
        {% endif %}
        {% for error in field.errors %}
          <p style="color: red">{{ error }}</p>
        {% endfor %}
      </p>
    {% endfor %}
    <button type="submit">Sign up</button>
  </form>
{% endblock %}

beosztas/templates/weekly_shift.html
{% extends 'base.html' %}

{% block content %}
  <p>Eheti beosztásom</p>
    <table>
      <tr>
        <th>Nap</th>
        <th>Műszak</th>
        <th>Óra</th>
      </tr>
  {% for day in current_weekly_shift %}
      <tr>
        {% for field in day %}
        <td>
          {{ field }}
        </td>
        {% endfor %}
      </tr>
  {% endfor %}
    </table>
  <p>Jövőheti beosztásom</p>
    <table>
      <tr>
        <th>Nap</th>
        <th>Műszak</th>
        <th>Óra</th>
      </tr>
  {% for day in next_weekly_shift %}
      <tr>
        {% for field in day %}
        <td>
          {{ field }}
        </td>
        {% endfor %}
      </tr>
  {% endfor %}
    </table>
{% endblock %}